"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authController_1 = require("../controllers/authController");
const userController_1 = require("../controllers/userController");
const authRouter = (0, express_1.Router)();
authRouter.post("/login", authController_1.userLogin);
authRouter.post("/signup", userController_1.createUser);
authRouter.post("/logout", authController_1.userLogout);
exports.default = authRouter;
